# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e8933cf4dedbfda2ebb9a1416010ed3fff0fb99edf2746bb48847d23eb59e4b56ce081a8456fef0a7ea301d23a81207f895375fd138948ae9ff315e0e21c2b5a

test:
  secret_key_base: ef584aecbdb8e6594681461b4ce1fb9a5618cde0f0191c307babd6ff5b1cf675431cac95b8f1f9d46e15fa7dd0283aec4624e9285eba7cc760d33980e7f9cb61

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
